Routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Company\Http\Controllers\CompanyController;

Route::resource('companies', CompanyController::class)->middleware('auth')->middleware('verified');
Route::get('/getEmployees', [\Modules\Company\Http\Controllers\GetEmployeeController::class, 'getEmployee'])->name('companies.getEmployees');

Entities/Company.php
<?php

namespace Modules\Company\Entities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Modules\Employee\Entities\Employee;

class Company extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'website', 'logo', 'company_id'];

    public function employee()
    {
        return $this->hasMany(Employee::class, 'company_id', 'id');
    }
}

Http/Controllers/CompanyController.php
<?php

namespace Modules\Company\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Company\Entities\Company;
use Spatie\Image\Image;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('company::companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create()
    {
        return view('company::companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Company $company)
    {
        $validate_data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => 'unique',
            'email' => ['required', 'string', 'email', 'max:255', 'unique:companies'],
            'website' => ['required', 'max:255'],
            'logo' => 'image',
        ]);
        $company = Company::create([
            'name' => $validate_data['name'],
            'email' => $validate_data['email'],
            'website' => $validate_data['website'],
            'slug' => $validate_data['name'],
            'logo' => $validate_data['logo'],
        ]);
        $company->logo->move('storage', $company->name);
        $path ='storage/'.$company->name;

        $pathlogo = 'storage/'.$company->name.'logo';
        Image::load($path)
            ->width(150)
            ->save($pathlogo);

        $pathsize2 = 'storage/'.$company->name.'size2';
        Image::load($path)
            ->width(300)
            ->save($pathsize2);

        $pathsize3 = 'storage/'.$company->name.'size3';
        Image::load($path)
            ->width(500)
            ->save($pathsize3);



        return redirect()->route('companies.index');
    }

    /**
     * Show the specified resource.
     *
     * @param  Company  $company
     * @return Application|Factory|View
     */
    public function show(Company $company)
    {
        return view('company::companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Company  $company
     * @return Application|Factory|View
     */
    public function edit(Company $company)
    {
        return view('company::companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Company $company)
    {
        $validate_data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => 'unique',
            'email' => ['required', 'string', 'email', 'max:255'],
            'website' => ['required', 'max:255'],
        ]);

        if ($request['logo']) {
            $company->update([
                'logo' => $request['logo'],
            ]);

            $company->logo->move('storage', $company->name);
        }

        $company->update([
            'name' => $validate_data['name'],
            'email' => $validate_data['email'],
            'website' => $validate_data['website'],
            'slug' => $validate_data['name'],
        ]);

        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Company  $company
     * @return RedirectResponse
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('companies.index');
    }
}

Http/Controllers/GetEmployeeController.php
<?php

namespace Modules\Company\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Routing\Controller;
use Modules\Company\Entities\Company;

class GetEmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function getEmployee()
    {
        return view('company::companies.getEmployee', [
            'companies' => Company::with('employee')->get(),
        ]);
    }
}

Resources/views/companies/create.blade.php
@extends('company::layouts.app')

@section('content')
    @if($errors->any())
        <div class="alert alert-danger" >
            <ul>
                @foreach($errors->all() as $error)
                    <li>
                        {{$error}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Create New Company</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
                </div>
            </div>
        </div>

        <div class="container">
            <form action="{{route('companies.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-row">
                    <div class="col-md-2"></div>

                    <div class="form-group col-md-4">
                        <label for="name">Company Name:</label>
                        <input type="text" name="name" class="form-control" autofocus>
                    </div>


                    <div class="form-group col-md-4">
                        <label for="email">Company Email:</label>
                        <input type="email" name="email" class="form-control" >
                    </div>

                    <div class="col-md-2"></div>

                    <div class="form-group col-md-4">
                        <label for="website">Company Website:</label>
                        <input type="text" name="website" class="form-control" >
                    </div>

                    <div class="form-group col-md-4">
                        <label for="logo">Company Logo:</label>
                        <input type="file" name="logo" class="form-control" >
                    </div>

                    <div class="col-md-2"></div>


                    <div class="form-group col-md-4">
                        <button type="submit" class="btn btn-primary ml-3">Submit</button>                        <div class="col-md-2"></div>
                    </div>
                </div>
            </form>
        </div>
@endsection

Resources/views/companies/edit.blade.php
@extends('company::layouts.app')

@section('content')
    @if($errors->any())
        <div class="alert alert-danger" >
            <ul>
                @foreach($errors->all() as $error)
                    <li>
                        {{$error}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Edit Company</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('companies.index') }}" > Back</a>
                </div>
            </div>
        </div>
        <form action="/companies/{{$company->id}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('put') }}


            <div class="form-row">
                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                    <label for="name">name</label>
                    <input type="text" name="name" class="form-control" value="{{$company->name}}">
                </div>

                <div class="form-group col-md-4">
                    <label for="email">email</label>
                    <input type="email" name="email" class="form-control" value="{{$company->email}}">
                </div>

                <div class="col-md-2"></div>


            </div>

            <div class="form-row">
                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                    <label for="website">website</label>
                    <input type="text" name="website" class="form-control" value="{{$company->website}}">
                </div>


            </div>

            <div class="form-row">
                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                    <label for="logo">logo</label>
                    <input type="file" name="logo" class="form-control" placeholder="Company logo">
                    <img src="{{asset('/storage/'.$company->name)}}" height="50" width="50">

                </div>


                <div class="form-group col-md-4">
                    <button class="btn btn-info">update</button>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </form

@endsection

Resources/views/companies/getEmployee.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<body>

@foreach ($companies as $company)

    <p>  name: {{$company->name}} =>

        employee name: {{$company->employee}} <br>
    </p>
@endforeach



</body>
</html>

Resources/views/companies/show.blade.php
@extends('company::layouts.app')

@section('content')

    <div class="container">
        <div class="container mt-2">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Company Information</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12"></div>

                <div class="panel panel-default table-responsive">

                    <table class="table table-condensed">
                        <thead>
                        <tr>

                            <th class="text-center">Company_Name</th>
                            <th class="text-center">Company_Email</th>
                            <th class="text-center">Company_Website</th>
                            <th class="text-center">Company_Logo</th>


                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="text-center">{{ $company->name }}</td>
                            <td class="text-center">{{ $company->email }}</td>
                            <td class="text-center">{{ $company->website }}</td>
                            <td class="text-center"><img src="{{asset('/storage/'.$company->name.'logo')}}"></td>


                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>


@endsection

Resources/views/index.blade.php
@extends('company::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('company.name') !!}
    </p>
@endsection

Resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Company</title>
    <link rel="icon"  href="{{ URL::asset('img/icon.png') }}">


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-5.0.2-dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="/datatables.min.css">


    @vite(['resources/js/app.js'])

</head>
<body>
<div class="mb-3">

    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('companies.index')}}">Company list</a>
                            </li>
                            <li class="nav-item">
{{--                                <a class="nav-link " href="{{route('employees.index')}}">Employee list</a>--}}
                            </li>

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</div>
<script src="/jquery.min.js"></script>
<!-- DataTables -->
<script src="/datatables.min.js"></script>
<!-- Bootstrap JavaScript -->
<script src="/bootstrap-5.0.2-dist/js/bootstrap.min.js"></script>
<!-- App scripts -->
@stack('scripts')
</body>
</html>

Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module Company</title>

       {{-- Laravel Vite - CSS File --}}
       {{-- {{ module_vite('build-company', 'Resources/assets/sass/app.scss') }} --}}

    </head>
    <body>
        @yield('content')

        {{-- Laravel Vite - JS File --}}
        {{-- {{ module_vite('build-company', 'Resources/assets/js/app.js') }} --}}
    </body>
</html>